version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: whitny5963
      MYSQL_USER: root
      MYSQL_DATABASE: universidad
    ports:
      -"3306:3306"
    volumes:
      -../Proyecto_Final_OLIST/api/db/universidad:/var/lib/mysql:rw
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      -../Proyecto_Final_OLIST/api:/app
    ports:
      -"8000:8000"
    depends_on:
      - db